package sqlinjection

import (
	"regexp"
	"strings"

	"github.com/AikidoSec/firewall-go/internal/zeninternals"
)

const (
	sqlInjectionSafe             = 0
	sqlInjectionDetected         = 1
	sqlInjectionInternalError    = 2
	sqlInjectionFailedToTokenize = 3
)

func detectSQLInjection(query string, userInput string, dialect int) int {
	// Lowercase versions of query and user input
	queryLowercase := strings.ToLower(query)
	userInputLowercase := strings.TrimSpace(strings.ToLower(userInput))

	if shouldReturnEarly(queryLowercase, userInputLowercase) {
		return sqlInjectionSafe
	}

	return zeninternals.DetectSQLInjection(queryLowercase, userInputLowercase, dialect)
}

var isAlphanumeric = regexp.MustCompile(`^[a-zA-Z0-9_]+$`).MatchString
var isDigits = regexp.MustCompile(`^\d+$`).MatchString

// SQL keywords that can be used in injection attacks and should not be considered safe
// even if they are alphanumeric. This list includes keywords that can alter query logic
// or structure when concatenated into SQL statements.
var dangerousSQLKeywords = map[string]bool{
	"or":                                  true,
	"and":                                 true,
	"union":                               true,
	"select":                              true,
	"insert":                              true,
	"update":                              true,
	"delete":                              true,
	"drop":                                true,
	"create":                              true,
	"alter":                               true,
	"exec":                                true,
	"execute":                             true,
	"where":                               true,
	"from":                                true,
	"join":                                true,
	"having":                              true,
	"order":                               true,
	"group":                               true,
	"limit":                               true,
	"offset":                              true,
	"into":                                true,
	"values":                              true,
	"set":                                 true,
	"table":                               true,
	"database":                            true,
	"schema":                              true,
	"procedure":                           true,
	"function":                            true,
	"trigger":                             true,
	"view":                                true,
	"index":                               true,
	"grant":                               true,
	"revoke":                              true,
	"commit":                              true,
	"rollback":                            true,
	"truncate":                            true,
	"declare":                             true,
	"cast":                                true,
	"convert":                             true,
	"case":                                true,
	"when":                                true,
	"then":                                true,
	"else":                                true,
	"end":                                 true,
	"exists":                              true,
	"in":                                  true,
	"like":                                true,
	"between":                             true,
	"is":                                  true,
	"null":                                true,
	"not":                                 true,
	"all":                                 true,
	"any":                                 true,
	"some":                                true,
	"distinct":                            true,
	"as":                                  true,
	"on":                                  true,
	"using":                               true,
	"natural":                             true,
	"cross":                               true,
	"inner":                               true,
	"outer":                               true,
	"left":                                true,
	"right":                               true,
	"full":                                true,
	"asc":                                 true,
	"desc":                                true,
	"by":                                  true,
	"with":                                true,
	"recursive":                           true,
	"intersect":                           true,
	"except":                              true,
	"minus":                               true,
	"for":                                 true,
	"lock":                                true,
	"nowait":                              true,
	"skip":                                true,
	"locked":                              true,
	"share":                               true,
	"mode":                                true,
	"wait":                                true,
	"primary":                             true,
	"foreign":                             true,
	"key":                                 true,
	"references":                          true,
	"constraint":                          true,
	"unique":                              true,
	"check":                               true,
	"default":                             true,
	"cascade":                             true,
	"restrict":                            true,
	"action":                              true,
	"no":                                  true,
	"add":                                 true,
	"column":                              true,
	"modify":                              true,
	"change":                              true,
	"rename":                              true,
	"to":                                  true,
	"if":                                  true,
	"begin":                               true,
	"transaction":                         true,
	"work":                                true,
	"savepoint":                           true,
	"release":                             true,
	"prepare":                             true,
	"deallocate":                          true,
	"describe":                            true,
	"explain":                             true,
	"show":                                true,
	"use":                                 true,
	"call":                                true,
	"return":                              true,
	"returns":                             true,
	"language":                            true,
	"replace":                             true,
	"temporary":                           true,
	"temp":                                true,
	"global":                              true,
	"local":                               true,
	"session":                             true,
	"names":                               true,
	"charset":                             true,
	"collate":                             true,
	"character":                           true,
	"binary":                              true,
	"ascii":                               true,
	"unicode":                             true,
	"escape":                              true,
	"regexp":                              true,
	"rlike":                               true,
	"sounds":                              true,
	"interval":                            true,
	"extract":                             true,
	"position":                            true,
	"substring":                           true,
	"trim":                                true,
	"leading":                             true,
	"trailing":                            true,
	"both":                                true,
	"coalesce":                            true,
	"nullif":                              true,
	"ifnull":                              true,
	"isnull":                              true,
	"current_date":                        true,
	"current_time":                        true,
	"current_timestamp":                   true,
	"current_user":                        true,
	"session_user":                        true,
	"system_user":                         true,
	"user":                                true,
	"row":                                 true,
	"rows":                                true,
	"range":                               true,
	"unbounded":                           true,
	"preceding":                           true,
	"following":                           true,
	"partition":                           true,
	"over":                                true,
	"window":                              true,
	"frame":                               true,
	"exclude":                             true,
	"ties":                                true,
	"others":                              true,
	"groups":                              true,
	"filter":                              true,
	"within":                              true,
	"respect":                             true,
	"ignore":                              true,
	"nulls":                               true,
	"first":                               true,
	"last":                                true,
	"only":                                true,
	"lateral":                             true,
	"ordinality":                          true,
	"tablesample":                         true,
	"system":                              true,
	"bernoulli":                           true,
	"repeatable":                          true,
	"seed":                                true,
	"fetch":                               true,
	"next":                                true,
	"prior":                               true,
	"absolute":                            true,
	"relative":                            true,
	"forward":                             true,
	"backward":                            true,
	"scroll":                              true,
	"cursor":                              true,
	"open":                                true,
	"close":                               true,
	"move":                                true,
	"found":                               true,
	"goto":                                true,
	"continue":                            true,
	"exit":                                true,
	"loop":                                true,
	"while":                               true,
	"repeat":                              true,
	"until":                               true,
	"leave":                               true,
	"iterate":                             true,
	"handler":                             true,
	"condition":                           true,
	"sqlstate":                            true,
	"sqlwarning":                          true,
	"sqlexception":                        true,
	"undo":                                true,
	"deterministic":                       true,
	"contains":                            true,
	"sql":                                 true,
	"reads":                               true,
	"modifies":                            true,
	"data":                                true,
	"security":                            true,
	"definer":                             true,
	"invoker":                             true,
	"inout":                               true,
	"out":                                 true,
	"varargs":                             true,
	"variadic":                            true,
	"setof":                               true,
	"strict":                              true,
	"stable":                              true,
	"immutable":                           true,
	"volatile":                            true,
	"leakproof":                           true,
	"parallel":                            true,
	"safe":                                true,
	"unsafe":                              true,
	"cost":                                true,
	"support":                             true,
	"transform":                           true,
	"window_value":                        true,
	"aggregate":                           true,
	"analyze":                             true,
	"analyse":                             true,
	"vacuum":                              true,
	"cluster":                             true,
	"reindex":                             true,
	"checkpoint":                          true,
	"discard":                             true,
	"plans":                               true,
	"sequences":                           true,
	"domains":                             true,
	"types":                               true,
	"copy":                                true,
	"stdin":                               true,
	"stdout":                              true,
	"program":                             true,
	"delimiter":                           true,
	"quote":                               true,
	"header":                              true,
	"freeze":                              true,
	"verbose":                             true,
	"load":                                true,
	"extension":                           true,
	"comment":                             true,
	"owner":                               true,
	"listen":                              true,
	"notify":                              true,
	"unlisten":                            true,
	"lock_timeout":                        true,
	"statement_timeout":                   true,
	"idle_in_transaction_session_timeout": true,
	"search_path":                         true,
	"current_schema":                      true,
	"pg_sleep":                            true,
	"sleep":                               true,
	"waitfor":                             true,
	"delay":                               true,
	"benchmark":                           true,
	"information_schema":                  true,
	"pg_catalog":                          true,
	"mysql":                               true,
	"performance_schema":                  true,
	"sys":                                 true,
	"master":                              true,
	"msdb":                                true,
	"tempdb":                              true,
	"model":                               true,
	"xp_cmdshell":                         true,
	"sp_executesql":                       true,
	"sp_execute":                          true,
	"openrowset":                          true,
	"openquery":                           true,
	"opendatasource":                      true,
	"bulk":                                true,
	"outfile":                             true,
	"dumpfile":                            true,
	"infile":                              true,
	"load_file":                           true,
	"into_outfile":                        true,
	"into_dumpfile":                       true,
}

func shouldReturnEarly(query, userInput string) bool {
	// User input too small or larger than query
	if len(userInput) <= 1 || len(query) < len(userInput) {
		return true
	}

	// User input not in query
	if !strings.Contains(query, userInput) {
		return true
	}

	// User input is alphanumerical (with underscores allowed)
	// BUT check if it's a dangerous SQL keyword first
	if isAlphanumeric(userInput) {
		// Check if the alphanumeric input is a dangerous SQL keyword
		if dangerousSQLKeywords[userInput] {
			// This is a SQL keyword that could be used in injection attacks
			// Do not return early - let the full detection run
			return false
		}
		return true
	}

	// Check if user input is a valid comma-separated list of numbers
	cleanedInputForList := strings.ReplaceAll(strings.ReplaceAll(userInput, " ", ""), ",", "")
	match := isDigits(cleanedInputForList)
	return match
}
