name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build_libs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [	ubuntu-20.04, ubuntu-22.04-arm ]
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install golang
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install -y golang-go

      - name: Setup
        run: make setup
      - name: Build Aikido Agent
        run: make build