name: Go Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.25" # Specify the Go version you want to use

      - name: Check Go formatting
        run: |
          gofmt -l -s .
          if [ "$(gofmt -l . | wc -l)" -ne 0 ]; then
            echo "Go code is not formatted. Please run 'gofmt -w .' to format your code."
            exit 1
          fi
